# Generated by Django 3.2.7 on 2021-10-01 13:21

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('file', models.FileField(storage='PilotStreamingProject.storages.StaticStorage', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])])),
                ('streaming_url', models.URLField(max_length=5000)),
                ('ext', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
