# Generated by Django 3.2.7 on 2021-10-01 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_stream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])]),
        ),
    ]
